name: Build log_to_file
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - name: Compile
        run: |
          zig build -Dexample=defaults
          zig build -Dexample=defaults -Doptimize=ReleaseFast
